function [x0, map] = ironair_system_initial_state(p, I_cell_A)
%IRONAIR_SYSTEM_INITIAL_STATE Consistent initial state for the coupled plant.
%   [X0, MAP] = IRONAIR_SYSTEM_INITIAL_STATE(P, I_CELL_A)
%
%   Requirements: SRS018, SRS023.

arguments
    p (1, 1) struct
    I_cell_A (1, 1) double = 0
end

map = ironair_system_layout(p);
x_cell = ironair_cell_initial_state(p, I_cell_A);
T0 = p.reference.T_initial_K;
n_gas = p.reference.p_ambient_Pa .* p.cell_geometry.V_gas_m3 ./ ...
    (p.constants.R_J_molK .* T0);
n_O2 = p.gas_properties.x_O2_dry_air .* n_gas;
n_inert = n_gas - n_O2;
x_bop = [ ...
    T0; T0; T0; ...
    n_O2; n_inert; 1; ...
    p.reservoir.V_reservoir_initial_m3; p.pumps.omega_nominal_rad_s; ...
    p.dc_bus.V_dc_initial_V; ...
    I_cell_A .* p.stack.N_parallel; p.dc_bus.V_dc_initial_V; ...
    0; 0; ...
    T0; ...
    0; ...
    0; ...
    1; 0; 0; ...
    p.reference.E_cell_eq_ref_V; 0; ...
    T0];
x0 = [x_cell; x_bop];
if numel(x0) ~= map.count
    error("ironair:system:StateSize", ...
        "Initial state length %d does not match layout %d.", numel(x0), map.count);
end
end
