function varargout = ironair_system_ode(t, x, p, scenario_name, history)
%IRONAIR_SYSTEM_ODE Coupled iron-air plant residual for ode15s.
%   DX = IRONAIR_SYSTEM_ODE(T, X, P, SCENARIO_NAME)
%   [DX, OUTPUTS, DIAGNOSTICS] = IRONAIR_SYSTEM_ODE(...)
%
%   The mass matrix is the identity. Algebraic constraints are returned as
%   residuals and are satisfied by the component closures inside this
%   residual, which is the base-MATLAB form passed to ode15s.
%
%   Equation: SYS-001 through SYS-007
%   Requirements: SRS001, SRS018, SRS019, SRS023.

arguments
    t (1, 1) double
    x (:, 1) double
    p (1, 1) struct
    scenario_name (1, 1) string
    history struct = struct()
end

map = ironair_system_layout(p);
if numel(x) ~= map.count
    error("ironair:system:StateSize", ...
        "Coupled state length %d does not match layout %d.", numel(x), map.count);
end
scenario = ironair_scenario_inputs(t, scenario_name, p);
scenario = apply_scenario_history(t, scenario, history, p);

x_cell = x(1:map.n_cell);
T_cell = x(map.thermal(1));
n_Fe = sum(x_cell(map.cell.metal(1:map.cell.n_nodes)));
n_FeOH2 = sum(x_cell(map.cell.metal(map.cell.n_nodes + (1:map.cell.n_nodes))));
SOC = n_Fe ./ max(n_Fe + n_FeOH2, 1e-12);
f_area = x(map.degradation(1));
R_extra = x(map.degradation(2));
V_reservoir = x(map.flow(1));
c_O2 = x_cell(map.cell.gdl(1:map.cell.n_gdl));

I_cell = scenario.I_cell_command_A;
if isfield(history, "I_cell_A")
    I_cell = history.I_cell_A;
end
if mean(c_O2) < 0.5 && I_cell > 0
    I_cell = I_cell .* mean(c_O2) ./ 0.5;
end
if SOC <= p.supervisory_controls.SOC_min
    I_cell = min(I_cell, 0);
elseif SOC >= p.supervisory_controls.SOC_max
    I_cell = max(I_cell, 0);
end
% Discharge cannot exceed the dissolved-oxygen film limit (AIR-008).
V_ely_limit = max(x_cell(map.cell.electrolyte(7)), 1e-9);
c_O2_liquid = max(x_cell(map.cell.electrolyte(4)) ./ V_ely_limit, 0);
c_KOH_limit = min(max(x_cell(map.cell.electrolyte(1)) ./ V_ely_limit, ...
    p.electrolyte.c_property_min_mol_m3), p.electrolyte.c_property_max_mol_m3);
D_O2_limit = ironair_O2_diffusivity(c_KOH_limit, T_cell, p);
j_lim_O2 = 4 .* p.constants.F_C_mol .* D_O2_limit .* c_O2_liquid ./ ...
    p.cell_geometry.delta_diffusion_m;
flood = min(max(x_cell(map.cell.air(1)), 0), 1);
I_oxygen_limit = 0.8 .* j_lim_O2 .* p.air_electrode.A_geometric_air_m2 .* (1 - flood);
if I_cell > I_oxygen_limit
    I_cell = max(I_oxygen_limit, 0);
end

fault_name = string(scenario.fault_name);
Q_leak = 0;
N_fan_command = 1;
if fault_name == "leak"
    Q_leak = max(p.electrolyte_circulation.Q_nominal_m3_s, 1e-6);
elseif fault_name == "fan_failed" || fault_name == "oxygen_starvation"
    N_fan_command = 0;
end

n_H2 = x_cell(map.cell.her);
n_dot_H2_vent = max(n_H2, 0) ./ 100;
V_ely = max(x_cell(map.cell.electrolyte(7)), 1e-9);
c_H2O = x_cell(map.cell.electrolyte(3)) ./ V_ely;
n_dot_H2O_boundary = -Q_leak .* c_H2O;

cell_inputs = struct( ...
    "I_cell_A", I_cell, ...
    "T_cell_K", T_cell, ...
    "f_area_scale", f_area, ...
    "R_extra_Ohm", R_extra, ...
    "n_dot_H2_vent_mol_s", n_dot_H2_vent, ...
    "n_dot_H2O_boundary_mol_s", n_dot_H2O_boundary, ...
    "dT_cell_dt", 0);
[dx_cell, cell, cell_diag] = ironair_cell_model(t, x_cell, cell_inputs, p);

if fault_name == "short"
    short_inputs = base_fault_inputs(cell, scenario, p, x, map, N_fan_command);
    short_inputs.fault_name = "short";
    [~, short_out] = ironair_fault_injection(t, x(map.sensor), short_inputs, p);
    cell_inputs.I_cell_A = I_cell + short_out.I_short_A;
    [dx_cell, cell, cell_diag] = ironair_cell_model(t, x_cell, cell_inputs, p);
    I_cell = cell_inputs.I_cell_A;
end

A_reaction = [sum(cell.metal.A_active_Fe_m2), cell.air.A_active_air_m2, cell.air.A_active_air_m2];
j_reaction = [mean(cell.metal.j_Fe_A_m2), cell.air.j_ORR_A_m2, cell.air.j_OER_A_m2];
eta_reaction = [mean(cell.metal.eta_Fe_V), cell.air.eta_ORR_V, cell.air.eta_OER_V];
hx_inputs = struct("T_hot_K", T_cell, "T_cold_in_K", scenario.T_coolant_in_K);
[hx, hx_diag] = ironair_heat_exchanger(t, hx_inputs, p);
thermal_inputs = struct( ...
    "I_cell_A", cell.I_cell_A, ...
    "R_ohmic_Ohm", cell.R_ohmic_Ohm, ...
    "A_reaction_m2", A_reaction, ...
    "j_reaction_A_m2", j_reaction, ...
    "eta_reaction_V", eta_reaction, ...
    "T_ambient_K", scenario.T_ambient_K, ...
    "m_dot_coolant_kg_s", p.heat_exchanger.m_dot_coolant_kg_s, ...
    "cp_coolant_J_kgK", p.heat_exchanger.cp_coolant_J_kgK, ...
    "T_coolant_out_K", hx.T_cold_out_K, ...
    "T_coolant_in_K", scenario.T_coolant_in_K, ...
    "Q_dot_collector_W", cell.collector.P_joule_W);
[dx_thermal, thermal, thermal_diag] = ironair_thermal_ode(t, x(map.thermal), thermal_inputs, p);

air_inputs = struct( ...
    "T_gas_K", x(map.thermal(3)), ...
    "n_dot_O2_ORR_mol_s", cell.air.n_dot_O2_ORR_mol_s, ...
    "n_dot_O2_OER_mol_s", cell.air.n_dot_O2_OER_mol_s, ...
    "n_dot_O2_transfer_mol_s", cell.electrolyte.n_dot_O2_transfer_mol_s, ...
    "N_fan_command", N_fan_command, ...
    "p_H2O_Pa", 0);
[dx_air, air, air_diag] = ironair_air_system_ode(t, x(map.air_system), air_inputs, p);

flow_inputs = struct( ...
    "rho_fluid_kg_m3", cell.electrolyte.rho_KOH_kg_m3, ...
    "mu_fluid_Pa_s", cell.electrolyte.mu_KOH_Pa_s, ...
    "c_i_in_mol_m3", cell.electrolyte.c_K_mol_m3, ...
    "c_i_tank_mol_m3", cell.electrolyte.c_K_mol_m3, ...
    "Q_leak_m3_s", Q_leak, ...
    "R_i_mol_m3s", 0);
[dx_flow, flow, flow_diag] = ironair_electrolyte_flow_ode(t, x(map.flow), flow_inputs, p);

stack_inputs = struct("V_cell_V", cell.V_cell_V, "I_cell_A", cell.I_cell_A);
[stack, stack_diag] = ironair_stack_model(t, stack_inputs, p);
P_HVAC = p.module.P_HVAC_rated_W .* min(1, max(0, ...
    (x(map.enclosure) - scenario.T_ambient_K) ./ 20));
enc_inputs = struct( ...
    "Q_dot_internal_W", thermal.Q_dot_generation_W, ...
    "Q_dot_HVAC_W", P_HVAC, ...
    "T_ambient_K", scenario.T_ambient_K);
[dx_enc, enc, enc_diag] = ironair_enclosure_model(t, x(map.enclosure), enc_inputs, p);

module_inputs = struct( ...
    "P_stack_W", stack.P_stack_W, ...
    "P_fan_W", air.P_fan_electric_W, ...
    "P_pump_W", flow.P_pump_electric_W, ...
    "P_HVAC_W", P_HVAC, ...
    "n_Fe_mol", n_Fe, ...
    "e_cell_eq_V", cell.e_cell_eq_V, ...
    "T_cell_K", T_cell, ...
    "E_dc_J", 0.5 .* p.dc_bus.C_dc_F .* x(map.dc).^2, ...
    "omega_pump_rad_s", x(map.flow(2)));
[module, module_diag] = ironair_module_model(t, module_inputs, p);

P_export = max(module.P_module_net_W, 0);
P_import = max(-module.P_module_net_W, 0);
I_line = 0;
if scenario.V_LL_V > 0
    I_line = module.P_module_net_W ./ (sqrt(3) .* scenario.V_LL_V);
end
inv_inputs = struct( ...
    "V_LL_V", scenario.V_LL_V, ...
    "I_line_A", I_line, ...
    "phi_power_rad", scenario.phi_power_rad, ...
    "P_ref_W", module.P_module_net_W, ...
    "Q_ref_var", 0);
[dx_inv, inv, inv_diag] = ironair_inverter(t, x(map.inverter), inv_inputs, p);

V_stack = max(stack.V_stack_V, 1e-3);
V_dc = x(map.dc);
% Auxiliary power stays on the AC side. The DC link carries stack power.
I_bus_stack = stack.P_stack_W ./ max(abs(V_dc), 1);
if V_dc >= V_stack
    i_ref = stack.I_stack_A;
else
    i_ref = I_bus_stack;
end
tau_current_s = 0.05;
di_desired = (i_ref - x(map.converter(1))) ./ tau_current_s;
if V_dc >= V_stack
    d_duty = 1 - (V_stack - p.dcdc_converter.L_converter_H .* di_desired) ./ max(V_dc, 1e-3);
else
    d_duty = (V_dc + p.dcdc_converter.L_converter_H .* di_desired) ./ V_stack;
end
d_duty = min(max(d_duty, 1e-4), 1 - 1e-4);
conv_inputs = struct("V_in_V", V_stack, "I_out_A", I_bus_stack, "d_duty", d_duty);
[dx_conv, conv, conv_diag] = ironair_dcdc_converter(t, x(map.converter), conv_inputs, p);
dc_inputs = struct("I_source_A", I_bus_stack, "I_load_A", I_bus_stack);
[dx_dc, dc, dc_diag] = ironair_dc_bus_ode(t, x(map.dc), dc_inputs, p);
prot_inputs = struct("I_A", stack.I_stack_A, "V_dc_V", V_dc, ...
    "precharge", abs(V_dc) < 0.9 .* p.dc_bus.V_dc_initial_V);
[prot, prot_diag] = ironair_electrical_protection(t, prot_inputs, p);

tr_inputs = struct( ...
    "V_primary_V", max(V_dc, 1), ...
    "I_secondary_A", I_line, ...
    "f_transformer_Hz", scenario.f_transformer_Hz, ...
    "B_peak_T", scenario.B_peak_T, ...
    "T_ambient_K", scenario.T_ambient_K);
[dx_tr, tr, tr_diag] = ironair_transformer(t, x(map.transformer), tr_inputs, p);

grid_inputs = struct( ...
    "f_grid_Hz", scenario.f_grid_Hz, ...
    "P_scheduled_W", scenario.P_scheduled_W, ...
    "V_grid_V", scenario.V_grid_V, ...
    "V_grid_measured_V", scenario.V_grid_measured_V, ...
    "dP_requested_dt", scenario.dP_requested_dt);
[grid, grid_diag] = ironair_grid_model(t, grid_inputs, p);
ride_inputs = struct("V_grid_pu", grid.V_grid_pu, "delta_f_grid_Hz", grid.delta_f_grid_Hz);
[dx_ride, ride, ride_diag] = ironair_der_ride_through(t, x(map.ride), ride_inputs, p);

V_est = max(abs(cell.V_cell_V), 0.2);
I_cap = min(p.electrical_protection.I_trip_A, p.dcdc_converter.I_limit_A);
P_converter_limit = V_est .* I_cap;
P_electrochemical_limit = V_est .* 20;
P_thermal_limit = max(thermal_derate_power(T_cell, p), 0);
P_oxygen_limit = V_est .* 20 .* min(1, max(mean(c_O2), 0));
P_grid_limit = max(abs(grid.P_command_W), 0);
ctrl_inputs = struct( ...
    "SOC", SOC, ...
    "T_cell_K", T_cell, ...
    "P_rated_W", p.reference.P_AC_rated_W, ...
    "P_charge_converter_limit_W", P_converter_limit, ...
    "P_charge_electrochemical_limit_W", P_electrochemical_limit, ...
    "P_charge_thermal_limit_W", P_thermal_limit, ...
    "P_charge_grid_limit_W", P_grid_limit, ...
    "P_discharge_converter_limit_W", P_converter_limit, ...
    "P_discharge_oxygen_limit_W", P_oxygen_limit, ...
    "P_discharge_electrochemical_limit_W", P_electrochemical_limit, ...
    "P_discharge_thermal_limit_W", P_thermal_limit, ...
    "I_ref_A", I_cell, ...
    "I_measured_A", cell.I_cell_A, ...
    "I_limit_A", I_cap, ...
    "grid_ready", ~ride.trip_command, ...
    "thermal_ready", T_cell < p.supervisory_controls.T_trip_K, ...
    "fluid_ready", V_reservoir > p.reservoir.V_reservoir_min_m3, ...
    "electrodes_ready", SOC > 0 && SOC < 1);
[dx_ctrl, ctrl, ctrl_diag] = ironair_supervisory_controller( ...
    t, x(map.controller), ctrl_inputs, p);

Q_BOL = 2 .* p.constants.F_C_mol .* ...
    (p.cell_geometry.n_Fe_initial_mol + p.cell_geometry.n_FeOH2_initial_mol);
Q_now = cell.Q_Fe_theoretical_C;
est_inputs = struct( ...
    "Q_usable_C", max(Q_now, 1), ...
    "I_Fe_storage_A", cell.I_Fe_A, ...
    "y_measured", SOC, ...
    "y_predicted", x(map.sensor(1)) .* 0 + x(1) .* 0 + SOC, ...
    "L_observer", 0.05, ...
    "x_hat_previous", SOC, ...
    "u_input", struct("dt_s", 0, "I_Fe_storage_A", cell.I_Fe_A, "Q_usable_C", max(Q_now, 1)), ...
    "H_EKF", 1, ...
    "P_pred", 0.01, ...
    "R_measurement", 1e-4, ...
    "Q_usable_current_C", max(Q_now, 0), ...
    "Q_usable_BOL_C", Q_BOL);
est_inputs.y_predicted = x(map.degradation(1)) .* 0 + SOC;
[dx_est, est, est_diag] = ironair_state_estimator(t, SOC, est_inputs, p);

deg_inputs = struct( ...
    "T_cell_K", T_cell, ...
    "I_cell_A", cell.I_cell_A, ...
    "SOC", SOC, ...
    "A_active_m2", sum(cell.metal.A_active_Fe_m2), ...
    "a_catalyst", x_cell(map.cell.air(2)), ...
    "Q_usable_BOL_C", Q_BOL);
[dx_deg, deg, deg_diag] = ironair_degradation_ode(t, x(map.degradation), deg_inputs, p);
dx_cell(map.cell.metal(1)) = dx_cell(map.cell.metal(1)) - deg.dn_Fe_inactive_dt;
dx_cell(map.cell.air(2)) = dx_cell(map.cell.air(2)) + deg.da_catalyst_dt;
dx_cell(map.cell.air(3)) = dx_cell(map.cell.air(3)) + deg.da_catalyst_dt;

fault_inputs = base_fault_inputs(cell, scenario, p, x, map, N_fan_command);
fault_inputs.Q_electrolyte_in_m3_s = flow.Q_pump_m3_s;
fault_inputs.Q_electrolyte_out_m3_s = flow.Q_pump_m3_s;
fault_inputs.Q_leak_m3_s = Q_leak;
fault_inputs.N_fan = x(map.air_system(3));
fault_inputs.N_fan_command = 1;
[dx_fault, fault, fault_diag] = ironair_fault_injection(t, x(map.sensor), fault_inputs, p);

net = ironair_reaction_network();
r_reactions = zeros(numel(net.reactions), 1);
r_reactions(net.idx.Fe_ox) = sum(cell.metal.r_Fe_ox_mol_s);
r_reactions(net.idx.magnetite) = sum(cell.metal.r_mag_mol_s);
r_reactions(net.idx.ORR) = cell.air.r_ORR_mol_s;
r_reactions(net.idx.OER) = cell.air.r_OER_mol_s;
r_reactions(net.idx.HER) = cell.her.r_HER_mol_s;
r_reactions(net.idx.carbonation) = cell.electrolyte.r_carbonation_mol_s;
q_boundary = zeros(numel(net.species), 1);
q_boundary(net.idx.H2O) = n_dot_H2O_boundary;
q_boundary(net.idx.O2) = cell.electrolyte.n_dot_O2_transfer_mol_s - cell.air.n_dot_O2_ORR_mol_s + cell.air.n_dot_O2_OER_mol_s;
% SYS-001: central species inventory. Conservation law.
dn_species_dt = net.S * r_reactions + net.B_boundary * q_boundary;
% SYS-002: elemental closure of the stoichiometric matrix. Conservation law.
e_element_balance = net.A_elements * net.S;
element_ok = norm(e_element_balance, inf) <= 1e-9;
% SYS-003: Kirchhoff current residual. Conservation law.
e_current_balance = cell_diag.e_current_negative;
current_ok = abs(e_current_balance) <= 1e-6;

H_dot_material_in = air.n_dot_O2_in_mol_s .* p.gas_properties.M_dry_air_kg_mol .* ...
    p.gas_properties.cp_air_J_kgK .* scenario.T_ambient_K;
H_dot_material_out = air.n_dot_O2_out_mol_s .* p.gas_properties.M_dry_air_kg_mol .* ...
    p.gas_properties.cp_air_J_kgK .* x(map.thermal(3));
Q_dot_boundary = -thermal.Q_dot_convection_W - thermal.Q_dot_radiation_W - thermal.Q_dot_coolant_W;
W_dot_in = P_import + flow.P_pump_electric_W + air.P_fan_electric_W;
W_dot_out = P_export;
% SYS-004: open-system energy balance. Conservation law.
dU_system_dt = H_dot_material_in - H_dot_material_out + Q_dot_boundary + W_dot_in - W_dot_out;

% SYS-005: AC round trip over a supplied history, including auxiliary loads.
eta_round_trip_AC = NaN;
if isfield(history, "t_sim")
    E_grid_export_J = trapz(history.t_sim, history.P_grid_export_W);
    E_grid_import_J = trapz(history.t_sim, history.P_grid_import_W);
    eta_round_trip_AC = E_grid_export_J ./ max(E_grid_import_J, realmin);
end

if p.fidelity_level <= 1
    dx_conv = zeros(size(dx_conv));
    dx_dc = 0;
    dx_inv = zeros(size(dx_inv));
    dx_tr = 0;
    dx_ctrl = 0;
    dx_ride = 0;
end
dx = zeros(map.count, 1);
dx(1:map.n_cell) = dx_cell;
dx(map.thermal) = dx_thermal;
dx(map.air_system) = dx_air;
dx(map.flow) = dx_flow;
dx(map.dc) = dx_dc;
dx(map.converter) = dx_conv;
dx(map.inverter) = dx_inv;
dx(map.transformer) = dx_tr;
dx(map.controller) = dx_ctrl;
dx(map.ride) = dx_ride;
dx(map.degradation) = dx_deg;
dx(map.sensor) = dx_fault;
dx(map.enclosure) = dx_enc;
% The estimator's continuous SOC derivative is reported. Inventory SOC remains
% the plant state, so the observer formula is not integrated a second time.
% SYS-006: identity mass matrix. M_system * dx_dt = f_system.
M_system = eye(map.count);
f_system = dx;
% SYS-007
e_algebraic = [air_diag.ideal_gas_residual_J; e_current_balance; ...
    norm(e_element_balance, inf); tr.turns_residual; conv.power_residual_W];

outputs = struct( ...
    "cell", cell, ...
    "thermal", thermal, ...
    "air", air, ...
    "flow", flow, ...
    "stack", stack, ...
    "module", module, ...
    "enclosure", enc, ...
    "dc", dc, ...
    "converter", conv, ...
    "inverter", inv, ...
    "transformer", tr, ...
    "grid", grid, ...
    "ride", ride, ...
    "controller", ctrl, ...
    "estimator", est, ...
    "degradation", deg, ...
    "fault", fault, ...
    "protection", prot, ...
    "heat_exchanger", hx, ...
    "SOC", SOC, ...
    "I_cell_A", I_cell, ...
    "dn_species_dt", dn_species_dt, ...
    "dU_system_dt", dU_system_dt, ...
    "eta_round_trip_AC", eta_round_trip_AC, ...
    "P_grid_export_W", P_export, ...
    "P_grid_import_W", P_import, ...
    "V_cell_V", cell.V_cell_V, ...
    "e_algebraic", e_algebraic);
diagnostics = struct( ...
    "t", t, ...
    "M_system", M_system, ...
    "f_system", f_system, ...
    "e_element_balance", e_element_balance, ...
    "element_ok", element_ok, ...
    "e_current_balance", e_current_balance, ...
    "current_ok", current_ok, ...
    "e_algebraic", e_algebraic, ...
    "cell", cell_diag, ...
    "thermal", thermal_diag, ...
    "air", air_diag, ...
    "flow", flow_diag, ...
    "stack", stack_diag, ...
    "module", module_diag, ...
    "enclosure", enc_diag, ...
    "dc", dc_diag, ...
    "converter", conv_diag, ...
    "inverter", inv_diag, ...
    "transformer", tr_diag, ...
    "grid", grid_diag, ...
    "ride", ride_diag, ...
    "controller", ctrl_diag, ...
    "estimator", est_diag, ...
    "degradation", deg_diag, ...
    "fault", fault_diag, ...
    "protection", prot_diag, ...
    "heat_exchanger", hx_diag, ...
    "eta_round_trip_AC", eta_round_trip_AC);
if any(~isfinite(dx))
    error("ironair:system:NonfiniteResidual", ...
        "The coupled residual is nonfinite at t = %g s.", t);
end
varargout{1} = dx;
if nargout > 1
    varargout{2} = outputs;
end
if nargout > 2
    varargout{3} = diagnostics;
end
end

function inputs = base_fault_inputs(cell, scenario, p, x, map, N_fan_command)
e_oc = cell.e_cell_eq_V - cell.eta_loss_kin_V - cell.eta_loss_conc_V;
inputs = struct( ...
    "y_true", cell.V_cell_V, ...
    "sensor_noise", scenario.sensor_noise, ...
    "fault_name", scenario.fault_name, ...
    "Q_electrolyte_in_m3_s", 0, ...
    "Q_electrolyte_out_m3_s", 0, ...
    "N_fan", x(map.air_system(3)), ...
    "N_fan_command", N_fan_command, ...
    "V_cell_V", cell.V_cell_V, ...
    "R_ohmic_Ohm", max(cell.R_ohmic_Ohm, 1e-6), ...
    "e_oc_V", e_oc, ...
    "I_external_A", cell.I_cell_A);
end

function scenario = apply_scenario_history(t, scenario, history, p)
if isempty(fieldnames(history))
    return
end
direct = ["T_ambient_K", "T_coolant_in_K", "V_grid_V", "V_grid_measured_V", ...
    "f_grid_Hz", "fault_name", "P_scheduled_W", "sensor_noise", "phi_power_rad", ...
    "V_LL_V", "f_transformer_Hz", "B_peak_T", "dP_requested_dt"];
if isfield(history, "I_cell_A")
    scenario.I_cell_command_A = history.I_cell_A;
end
for index = 1:numel(direct)
    name = direct(index);
    if isfield(history, name)
        scenario.(name) = history.(name);
    end
end
if ~isfield(history, "fault_schedule")
    return
end
schedule = history.fault_schedule;
names = fieldnames(schedule);
for index = 1:numel(names)
    item = schedule.(names{index});
    if ~isstruct(item) || ~isfield(item, "onset_s") || ~isfield(item, "duration_s")
        continue
    end
    active = t >= item.onset_s && t < item.onset_s + item.duration_s;
    if ~active
        continue
    end
    switch string(names{index})
        case "fan_failure"
            scenario.fault_name = "fan_failed";
        case "electrolyte_leak"
            scenario.fault_name = "leak";
        case "cell_short"
            scenario.fault_name = "short";
        case "oxygen_starvation"
            scenario.fault_name = "oxygen_starvation";
        case "grid_undervoltage"
            scenario.V_grid_V = 0.5 .* p.grid.V_grid_base_V;
            scenario.V_grid_measured_V = scenario.V_grid_V;
    end
end
end

function P_allowed = thermal_derate_power(T_cell, p)
span = p.supervisory_controls.T_trip_K - p.supervisory_controls.T_derate_K;
f_thermal = min(1, max(0, (p.supervisory_controls.T_trip_K - T_cell) ./ span));
P_allowed = f_thermal .* p.reference.P_AC_rated_W;
end
