function outputs = ironair_sim_plant_components(resolution_name)
%IRONAIR_SIM_PLANT_COMPONENTS Evaluate each balance-of-plant component once.
%   OUTPUTS = IRONAIR_SIM_PLANT_COMPONENTS(RESOLUTION_NAME) exercises the
%   thermal, air, flow, electrical, grid, control, estimator, degradation,
%   and fault equations at one documented reference state. The coupled
%   scenarios call these same functions.
%
%   Requirements: SRS008 through SRS018.

arguments
    resolution_name (1, 1) string = "smoke"
end

ironair_setup();
p = ironair_configuration_profile("single_cell", resolution_name);
T = p.reference.T_initial_K;
outputs = struct();
outputs.heat_exchanger = ironair_heat_exchanger(0, struct( ...
    "T_hot_K", T + 10, "T_cold_in_K", T), p);
[~, outputs.thermal] = ironair_thermal_ode(0, T * ones(3, 1), struct( ...
    "I_cell_A", 1, "R_ohmic_Ohm", 0.01, "A_reaction_m2", [1, 1, 1], ...
    "j_reaction_A_m2", [1, 0, 0], "eta_reaction_V", [0.05, 0, 0], ...
    "T_ambient_K", T, "m_dot_coolant_kg_s", 0.01, "cp_coolant_J_kgK", 4180, ...
    "T_coolant_out_K", T + 1, "T_coolant_in_K", T, "Q_dot_collector_W", 0.01), p);
n_gas = p.reference.p_ambient_Pa * p.cell_geometry.V_gas_m3 / (p.constants.R_J_molK * T);
[~, outputs.air] = ironair_air_system_ode(0, [0.2095 * n_gas; 0.7905 * n_gas; 1], struct( ...
    "T_gas_K", T, "n_dot_O2_ORR_mol_s", 1e-6, "n_dot_O2_OER_mol_s", 0, ...
    "N_fan_command", 1), p);
[~, outputs.flow] = ironair_electrolyte_flow_ode(0, ...
    [p.reservoir.V_reservoir_initial_m3; p.pumps.omega_nominal_rad_s], struct( ...
    "rho_fluid_kg_m3", 1200, "mu_fluid_Pa_s", 0.002, ...
    "c_i_in_mol_m3", 6000, "c_i_tank_mol_m3", 6000), p);
outputs.stack = ironair_stack_model(0, struct("V_cell_V", 1.1, "I_cell_A", 1), p);
[~, outputs.dc] = ironair_dc_bus_ode(0, p.dc_bus.V_dc_initial_V, struct( ...
    "I_source_A", 1, "I_load_A", 1), p);
[~, outputs.converter] = ironair_dcdc_converter(0, [1; p.dc_bus.V_dc_initial_V], struct( ...
    "V_in_V", 1.1, "I_out_A", 1.1 / p.dc_bus.V_dc_initial_V, ...
    "d_duty", 1 - 1.1 / p.dc_bus.V_dc_initial_V), p);
[~, outputs.inverter] = ironair_inverter(0, [0; 0], struct("V_LL_V", p.inverter.V_LL_rated_V, ...
    "I_line_A", 0, "phi_power_rad", 0, "P_ref_W", 0, "Q_ref_var", 0), p);
[~, outputs.transformer] = ironair_transformer(0, T, struct("V_primary_V", 1000, ...
    "I_secondary_A", 1, "f_transformer_Hz", 60, "B_peak_T", 1.2, "T_ambient_K", T), p);
outputs.grid = ironair_grid_model(0, struct("f_grid_Hz", p.grid.f_nominal_Hz, ...
    "P_scheduled_W", 0, "V_grid_V", p.grid.V_grid_base_V, ...
    "V_grid_measured_V", p.grid.V_grid_base_V, "dP_requested_dt", 0), p);
[~, outputs.ride] = ironair_der_ride_through(0, 0, struct("V_grid_pu", 1, "delta_f_grid_Hz", 0), p);
[~, outputs.controller] = ironair_supervisory_controller(0, 0, struct( ...
    "SOC", 0.5, "T_cell_K", T, "I_ref_A", 0, "I_measured_A", 0, "I_limit_A", 10, ...
    "grid_ready", true, "thermal_ready", true, "fluid_ready", true, ...
    "electrodes_ready", true, "P_rated_W", 100, ...
    "P_charge_converter_limit_W", 10, "P_charge_electrochemical_limit_W", 10, ...
    "P_charge_thermal_limit_W", 10, "P_charge_grid_limit_W", 10, ...
    "P_discharge_converter_limit_W", 10, "P_discharge_oxygen_limit_W", 10, ...
    "P_discharge_electrochemical_limit_W", 10, "P_discharge_thermal_limit_W", 10), p);
u = struct("dt_s", 0, "I_Fe_storage_A", 0, "Q_usable_C", 1e5);
[~, outputs.estimator] = ironair_state_estimator(0, 0.5, struct( ...
    "Q_usable_C", 1e5, "I_Fe_storage_A", 0, "y_measured", 0.5, "y_predicted", 0.5, ...
    "L_observer", 0.05, "x_hat_previous", 0.5, "u_input", u, "H_EKF", 1, ...
    "P_pred", 0.01, "R_measurement", 1e-4, "Q_usable_current_C", 1e5, ...
    "Q_usable_BOL_C", 1e5), p);
[~, outputs.degradation] = ironair_degradation_ode(0, [1; 0; 0], struct( ...
    "T_cell_K", T, "I_cell_A", 1, "SOC", 0.5, "A_active_m2", 1, ...
    "a_catalyst", 1, "Q_usable_BOL_C", 1e5), p);
[~, outputs.fault] = ironair_fault_injection(0, [1.1; 0], struct( ...
    "y_true", 1.1, "sensor_noise", 0, "fault_name", "none", ...
    "Q_electrolyte_in_m3_s", 0, "Q_electrolyte_out_m3_s", 0, ...
    "N_fan", 1, "N_fan_command", 1, "V_cell_V", 1.1, "R_ohmic_Ohm", 0.02, ...
    "e_oc_V", 1.2, "I_external_A", 1), p);
outputs.p = p;
end
